name: Python application

on:
  [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./requirements.txt
    - name: Test with pytest
      run: |
        python ./scripts/run_tests.py